AWSTemplateFormatVersion : "2010-09-09"
Description: "Driver Template for deploying S3 Bucket"

Parameters:
  project:
    Type: String
    Description:  Project Name
    Default: devops-poc
  app:
    Type: String
    Description:  Application Name
    Default: app   
  env:
    Type: String
    AllowedValues: 
     - prod
     - dev
     - qa
     - uat
    Description:  Environment Name
    Default: dev 
  s3ArtifactPath:
    Type: String
    Description: "Artifact Bucket Path"
    Default: "https://devops-training-poc-app-dev-us-east-1-007756798683.s3.amazonaws.com/code/cfn/services"

Resources:
  s3Bucket:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${s3ArtifactPath}/s3/s3-app.yml"
      Parameters:
        project: !Ref project
        app: !Ref app
        env: !Ref env
        bucketName: artifacts
        versioningStatus: Enabled
        indexDocument: index.html
        errorDocument: error.html

Outputs:
  s3Bucket:
    Description: S3 Bucket Stack
    Value: !Ref s3Bucket
    Export:
      Name: !Sub "${project}-${app}-${env}-s3BucketStack"